#!/usr/bin/env bash
set -e
cp /etc/opendkim_init/* /etc/opendkim/
chmod 700 /etc/opendkim_init
chmod 400 /etc/opendkim/mail.private
chmod 400 /etc/opendkim/mail.txt
chown -R opendkim.opendkim /etc/opendkim
rsyslogd
opendkim -vvv
while true; do sleep 1; done
