#!/usr/bin/env bash
set -e
cp /etc/opendkim_int/* /etc/opendkim
chmod 700 /etc/opendkim
chmod 400 /etc/opendkim/mail.private
chmod 400 /etc/opendkim/mail.txt
chown -R opendkim.opendkim /etc/opendkim
syslog-ng
opendkim -vvv
while true; do sleep 1; done

#tail -F /var/log/mail.log
