#!/bin/bash


# Generate a timestamp for the backup file
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_FILE="$OUTPUT_DIR/postgres_backup_$TIMESTAMP.sql"

touch /$BACKUP_FILE
pg_dumpall -W > ${BACKUP_FILE}

echo "Backup completed successfully. Backup file: $BACKUP_FILE"
