#!/bin/bash

echo "Content-Type: multipart/x-mixed-replace;boundary=ffmpeg"
echo "Cache-Control: no-cache"
echo ""
ffmpeg -rtsp_transport tcp -i "rtsp://$USER:$PASSWORD192.168.1.20:88/videoMain" -c:v mjpeg -q:v 1 -f mpjpeg -an -